POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user2@user.com",
    "password": "12345678"
}

###
GET http://localhost:3000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoidXNlcjJAdXNlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTYzMTA1NDg0NywiZXhwIjoxNjMxMDU0OTA3fQ.lhC8Tbu9rhSS1LNkKDhE-bGax2YjDRglU_vRi9vINAc